site_name: TeddyWarner.org
site_author: Teddy Warner
site_description: >-
    Project Portfolio and Documentation Site for Teddy Warner - A Student, Maker, Developer, Award Winning Designer & Graduate of the Fab Academy.

site_url: https://teddywarner.org/

repo_url: https://github.com/Twarner491/TeddyWarner.org
repo_name: Twarner491/TeddyWarner.org

copyright: Copyright &copy; 2021 - 2023 Teddy Warner

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/teddy-warner-880974200/
      name: Linked In - Teddy Warner
    - icon: fontawesome/brands/github
      link: https://github.com/Twarner491
      name: Github - Twarner491
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@teddywarner
      name: YouTube - @teddywarner
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/teddymakesstuff/
      name: Instagram - @teddymakesstuff
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WarnerTeddy
      name: Twitter - @WarnerTeddy
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/534164566649733120/
      name: Discord - Twarner#2592
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/mskz5e4dyzv4cb4kkn73iipq0?si=58a503e3c7a54eeb
      name: Spotify - Teddy Warner
    - icon: mug-saucer-solid
      link: https://www.buymeacoffee.com/teddywarner
      name: Buy Me A Coffee! :)
    - icon: fontawesome/solid/paper-plane
      link: mailto:<Twarner491@gmail.com>
      name: Email - Twarner491@gmail.com

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  language: en

  font:
    text: Fira Sans
    code: Ubuntu Mono

  logo: images/TeddyWarner.svg

  favicon: images/TW.svg

  icon:
    repo: fontawesome/brands/git-alt
                          
  features:
   - navigation.instant
   - navigation.top
   - navigation.tabs
   - navigation.expand
   - content.code.annotate
   - search.share
   - content.tabs.link

plugins:
  - material/search
  - tags

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.details
  - extra
  - smarty
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  #- social:
   #   cards: !ENV [CARDS, false]
   #   cards_font: Fira Sans
    #  cards_color:
    #    fill: "#5466CE" 
     #   text: "#FFFFFF"

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/index.js 
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home : index.md
  - About : About-Me/about.md
  - Projects:  feed.md
  - Machine Profiles: 
    - Laser Cutters :
      - Epliog Fusion Pro 48 : Machine-Profiles/FusionPro48.md
    - 3D Printers : 
      - Prusa I3 MK3S+ : Machine-Profiles/MK3S+.md
      - Klipper Enabled Ender 3 : Machine-Profiles/KlipperEnder3Profile.md
  - Fab Academy: "http://fabacademy.org/2021/labs/charlotte/students/theodore-warner/"