site_name: Teddy Warner
site_author: Teddy Warner
site_description: >-
    causa sui. // @WarnerTeddy

site_url: https://teddywarner.org/

repo_url: https://github.com/Twarner491/TeddyWarner.org
repo_name: Twarner491/TeddyWarner.org

copyright: >
  Copyright &copy; 2021 Teddy Warner

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Twarner491
      name: Github - Twarner491
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/teddy-warner-880974200/
      name: Linked In - Teddy Warner
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WarnerTeddy
      name: X - @WarnerTeddy
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@teddywarner
      name: YouTube - @teddywarner
    - icon: fontawesome/solid/paper-plane
      link: mailto:<Twarner491@gmail.com>
      name: Email - Twarner491@gmail.com

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  language: en

  font:
    text: Fira Sans
    code: Ubuntu Mono

  logo: assets/images/TeddyWarner.svg

  favicon: assets/images/favicon.png

  icon:
    repo: fontawesome/brands/git-alt
                          
  features:
   - navigation.instant
   - navigation.tracking
   - navigation.top
   - navigation.tabs
   - navigation.expand
   - content.code.annotate
   - search.share
   - search.suggest
   - content.tabs.link
   - announce.dismiss

plugins:
  - social
  - material/search
  - tags

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.details
  - extra
  - smarty
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  #- social:
   #   cards: !ENV [CARDS, false]
   #   cards_font: Fira Sans
    #  cards_color:
    #    fill: "#5466CE" 
     #   text: "#FFFFFF"

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/index.js 
  - assets/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home : https://teddywarner.org
  - Projects:  https://teddywarner.org/proj/
  - Writings:  https://teddywarner.org/writ/